added model User, AuthenticationService, HashUtil, UserDao
Ilya-brinchuk/jv-cinema-shop pull request #3
Opened 2021-02-02 19:33 UTC by Ilya-brinchuk

2021-02-02 20:53 UTC, RuslanIbIsh approved these changes

2021-02-03 07:39 UTC, KseniiaMakarova requested changes

2021-02-03 07:39 UTC, KseniiaMakarova commented on src/main/java/com/cinema/exception/AuthenticationException.java
> +
redundant empty line

2021-02-03 07:39 UTC, KseniiaMakarova commented on src/main/java/com/cinema/Main.java
> +        System.out.println(user.toString());
what gets printed out here?

2021-02-03 07:58 UTC, KseniiaMakarova approved these changes

2021-02-03 07:58 UTC, KseniiaMakarova commented on src/main/java/com/cinema/model/User.java
> +                + ", password='" + password + '\''
let's not make secure data visible

2021-02-03 10:32 UTC, merged