added models: Ticket, ShoppingCart
Ilya-brinchuk/jv-cinema-shop pull request #4
Opened 2021-02-03 17:23 UTC by Ilya-brinchuk

added ShoppingCartDao, ShoppingCartService
added TicketDao

2021-02-03 17:35 UTC, engineer027 approved these changes

2021-02-04 10:01 UTC, dmytro-hryhoruk requested changes

2021-02-04 10:01 UTC, dmytro-hryhoruk commented on src/main/java/com/cinema/dao/impl/ShoppingCartDaoImpl.java
> +                + "LEFT JOIN FETCH m.movie "
Do you need all of these joins?

2021-02-04 10:01 UTC, dmytro-hryhoruk commented on src/main/java/com/cinema/service/ShoppingCartService.java
> +     */
```suggestion

```

2021-02-04 10:01 UTC, dmytro-hryhoruk commented on src/main/java/com/cinema/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartDao.getByUser(user);
let's move adding a ticket to DB after getting shoppingCart

2021-02-04 10:38 UTC, dmytro-hryhoruk approved these changes

2021-02-04 10:46 UTC, merged