added CinemaHallController, MovieController,
Ilya-brinchuk/jv-cinema-shop pull request #7
Opened 2021-02-14 16:59 UTC by Ilya-brinchuk

MovieSessionController

2021-02-14 19:29 UTC, engineer027 approved these changes

2021-02-15 08:52 UTC, KseniiaMakarova requested changes

2021-02-15 08:52 UTC, KseniiaMakarova commented on src/main/java/com/cinema/controller/CinemaHallController.java
> +    private final MapperDto<CinemaHallResponseDto, CinemaHall, CinemaHallRequestDto> mapperDto;
```suggestion
    private final DtoMapper<CinemaHallResponseDto, CinemaHall, CinemaHallRequestDto> dtoMapper;
```

2021-02-15 08:52 UTC, KseniiaMakarova commented on src/main/java/com/cinema/controller/MovieSessionController.java
> +    @PutMapping("{id}")
```suggestion
    @PutMapping("/{id}")
```
is it working the same or no?

2021-02-15 08:52 UTC, KseniiaMakarova commented on src/main/java/com/cinema/controller/MovieSessionController.java
> +    @DeleteMapping("{id}")
```suggestion
    @DeleteMapping("/{id}")
```
here as well

2021-02-15 08:52 UTC, KseniiaMakarova commented on src/main/java/com/cinema/controller/MovieSessionController.java
> +                                   @RequestBody MovieSessionRequestDto movieSessionRequestDto) {
let's not pass the body here - only id

2021-02-15 08:52 UTC, KseniiaMakarova commented on src/main/java/com/cinema/dao/MovieSessionDao.java
> +    MovieSession delete(MovieSession movieSession);
```suggestion
    void delete(Long movieSessionId);
```

2021-02-15 08:52 UTC, KseniiaMakarova commented on src/main/java/com/cinema/dao/impl/MovieSessionDaoImpl.java
> +            session.delete(movieSession);
let's use `load()` method to get the session by id before deleting it

2021-02-15 08:52 UTC, KseniiaMakarova commented on src/main/java/com/cinema/model/dto/CinemaHallResponseDto.java
> +    private String description;
let's return capacity as well

2021-02-15 08:52 UTC, KseniiaMakarova commented on src/main/java/com/cinema/model/dto/MovieResponseDto.java
> +    private String title;
here description as well

2021-02-15 08:52 UTC, KseniiaMakarova commented on src/main/java/com/cinema/service/MapperDto.java
> +public interface MapperDto<T,E, Q> {
```suggestion
public interface DtoMapper<T, E, Q> {
```

2021-02-15 08:52 UTC, KseniiaMakarova commented on src/main/java/com/cinema/service/MapperDto.java
> +    E replaceWithEntity(Q requestDto);
```suggestion
    T mapToDto(E entity);

    E mapToEntity(Q requestDto);
```

2021-02-15 08:52 UTC, KseniiaMakarova commented on src/main/java/com/cinema/service/mapper/CinemaHallMapper.java
> +
redundant empty line

2021-02-15 08:52 UTC, KseniiaMakarova commented on src/main/java/com/cinema/service/mapper/MovieMapper.java
> +
same

2021-02-15 11:25 UTC, KseniiaMakarova requested changes

2021-02-15 11:25 UTC, KseniiaMakarova commented on src/main/java/com/cinema/service/impl/MovieSessionServiceImpl.java
> +
redundant empty line

2021-02-15 11:25 UTC, KseniiaMakarova commented on src/main/java/com/cinema/service/impl/MovieSessionServiceImpl.java
> +        return movieSessionDao.get(id).orElseThrow(() -> new DataProcessingException(""));
let's add informative message here?

2021-02-15 12:24 UTC, KseniiaMakarova approved these changes

2021-02-15 19:15 UTC, merged